name: BSP Yocto Build

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]  # Must match your runner labels

    steps:
      # Checkout the repository code 
      - name: Checkout repo
        uses: actions/checkout@v4

      # Ensure your build script is executable
      - name: Prepare build script
        run: chmod +x /home/test/build_test.sh

      # Run the BSP build
      - name: Build the BSP
        run: /home/test/build_test.sh

      # List build outputs
      - name: List build outputs
        run: ls -l /build

      # Upload build outputs as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bsp-build
          path: /build
